name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - id: checkout
      name: Checkout the Repo
      uses: actions/checkout@v3
    - id: deployment
      shell: bash
      working-directory: ./docs
      run: |
        pip3 install -r requirements.txt
        make html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
